In [ ]:
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from tensorflow.keras.utils import image_dataset_from_directory


In [4]:
training_set = image_dataset_from_directory(
    "./train",
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(224, 224),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    
)

Found 76515 files belonging to 4 classes.


In [23]:
validation_set = image_dataset_from_directory(
    "./val",
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(224, 224),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    
)

Found 21861 files belonging to 4 classes.


In [ ]:
traing_set = image_dataset_directory(
    "/.val",
)

In [7]:
training_set

<BatchDataset element_spec=(TensorSpec(shape=(None, 224, 224, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 4), dtype=tf.float32, name=None))>

In [8]:
INPUT_SHAPE = (224,224,3)

In [9]:
mobilenet = tf.keras.applications.MobileNetV3Large(
    input_shape=INPUT_SHAPE,
    alpha=1.0,
    minimalistic=False,
    include_top=True,
    weights="imagenet",
    input_tensor=None,
    classes=1000,
    pooling=None,
    dropout_rate=0.2,
    classifier_activation="softmax",
    include_preprocessing=True,
   
)

22661472/22661472 [==============================] - 7s 0us/step


In [11]:
model = tf.keras.models.Sequential()

In [13]:
model.add(tf.keras.Input(shape=INPUT_SHAPE))


In [14]:
model.add(mobilenet)

In [15]:
model.add(tf.keras.layers.Dense(units = 4,activation="softmax"))

In [18]:
metrics_list = ["accuracy"]

In [20]:
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),loss="categorical_crossentropy",metrics=metrics_list)

In [21]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 MobilenetV3large (Functiona  (None, 1000)             5507432   
 l)                                                              
                                                                 
 dense (Dense)               (None, 4)                 4004      
                                                                 
Total params: 5,511,436
Trainable params: 5,487,036
Non-trainable params: 24,400
_________________________________________________________________


In [24]:
training_history = model.fit(x=training_set,validation_data=validation_set,epochs=15)

Epoch 1/15
684/684 [==============================] - 149s 164ms/step - loss: 1.2601 - accuracy: 0.7908 - val_loss: 1.2076 - val_accuracy: 0.7528
Epoch 2/15
684/684 [==============================] - 112s 163ms/step - loss: 1.1336 - accuracy: 0.8099 - val_loss: 1.0862 - val_accuracy: 0.7856
Epoch 3/15
684/684 [==============================] - 111s 163ms/step - loss: 1.0310 - accuracy: 0.8877 - val_loss: 0.9903 - val_accuracy: 0.8764
Epoch 4/15
684/684 [==============================] - 132s 194ms/step - loss: 0.9405 - accuracy: 0.8935 - val_loss: 0.9088 - val_accuracy: 0.8730
Epoch 5/15
684/684 [==============================] - 111s 163ms/step - loss: 0.8603 - accuracy: 0.9212 - val_loss: 0.8319 - val_accuracy: 0.9459
Epoch 6/15
684/684 [==============================] - 112s 163ms/step - loss: 0.7887 - accuracy: 0.9584 - val_loss: 0.7596 - val_accuracy: 0.9533
Epoch 7/15
684/684 [==============================] - 111s 163ms/step - loss: 0.7217 - accuracy: 0.9646 - val_loss: 0.6867 -

In [50]:
y_true = []
y_pred = []

for images, labels in test_set:
    preds = model.predict(images)
    y_pred.extend(preds.argmax(axis=1))
    y_true.extend(labels.numpy().argmax(axis=1))

1/1 [==============================] - 0s 25ms/step


In [32]:
from sklearn.metrics import f1_score

y_true = []
y_pred = []

for images, labels in validation_set:
    preds = model.predict(images)
    y_pred.extend(preds.argmax(axis=1))
    y_true.extend(labels.numpy().argmax(axis=1))

print("F1 Score:", f1_score(y_true, y_pred, average='weighted'))

1/1 [==============================] - 1s 700ms/step
F1 Score: 0.9799009110586682


In [25]:
model.save("./Trained_eye_disease_model.h5")

In [26]:
training_history.history

{'loss': [1.2600539922714233,
  1.133647084236145,
  1.031029462814331,
  0.9404657483100891,
  0.8602982759475708,
  0.788734495639801,
  0.7217475175857544,
  0.6650471091270447,
  0.6117369532585144,
  0.5657565593719482,
  0.5230788588523865,
  0.479729026556015,
  0.4478338956832886,
  0.40839195251464844,
  0.37738049030303955],
 'accuracy': [0.7907689213752747,
  0.8098897337913513,
  0.887699544429779,
  0.8935089707374573,
  0.9212296009063721,
  0.9583733677864075,
  0.964640200138092,
  0.966332733631134,
  0.9684826731681824,
  0.9677507877349854,
  0.9682996869087219,
  0.9733772277832031,
  0.9728283286094666,
  0.9765793085098267,
  0.97776859998703],
 'val_loss': [1.2076177597045898,
  1.0862400531768799,
  0.9903339743614197,
  0.9088206887245178,
  0.8319485187530518,
  0.7595699429512024,
  0.6866543292999268,
  0.6302177309989929,
  0.5843736529350281,
  0.54543137550354,
  0.4968697726726532,
  0.4537760019302368,
  0.41945943236351013,
  0.385530948638916,
  0.360

In [28]:
#saving history 
import pickle
with open("Training_history.pkl","wb") as f:
     pickle.dump(training_history.history,f)

Model Evaluation

In [43]:
test_set = image_dataset_from_directory(
    "./test",
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(224, 224),
    shuffle=False,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    
)

Found 10933 files belonging to 4 classes.


In [35]:
test_loss,test_acc= model.evaluate(test_set)

342/342 [==============================] - 13s 37ms/step - loss: 0.4053 - accuracy: 0.9542


In [36]:
from sklearn.metrics import f1_score

y_true = []
y_pred = []

for images, labels in test_set:
    preds = model.predict(images)
    y_pred.extend(preds.argmax(axis=1))
    y_true.extend(labels.numpy().argmax(axis=1))

f1 = f1_score(y_true, y_pred, average='weighted')
print("F1 Score:", f1)

1/1 [==============================] - 0s 24ms/step
F1 Score: 0.9538841285637993


In [38]:
# evaluate
test_loss, test_acc = model.evaluate(test_set)

# f1 calculate
from sklearn.metrics import f1_score

y_true = []
y_pred = []

for images, labels in test_set:
    preds = model.predict(images)
    y_pred.extend(preds.argmax(axis=1))
    y_true.extend(labels.numpy().argmax(axis=1))

f1 = f1_score(y_true, y_pred, average='weighted')

print("Loss:", test_loss)
print("Accuracy:", test_acc)
print("F1 Score:", f1)

1/1 [==============================] - 0s 20ms/step
Loss: 0.4052761197090149
Accuracy: 0.9541754126548767
F1 Score: 0.9538841285637993


In [45]:
true_categories = tf.concat([y for x,y in test_set],axis=0)
true_categories

<tf.Tensor: shape=(10933, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       ...,
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]], dtype=float32)>

In [44]:
#computing predict label using test_case
predicted_categories = model.predict(test_set)
predicted_categories

342/342 [==============================] - 12s 36ms/step


array([[0.766778  , 0.05421979, 0.05131887, 0.12768337],
       [0.766778  , 0.05421979, 0.05131887, 0.12768337],
       [0.766778  , 0.05421979, 0.05131887, 0.12768337],
       ...,
       [0.09524688, 0.04988709, 0.04534262, 0.80952334],
       [0.09524688, 0.04988709, 0.04534262, 0.80952334],
       [0.09524688, 0.04988709, 0.04534262, 0.80952334]], dtype=float32)

classification report

In [54]:
from sklearn.metrics import classification_report
print(classification_report(y_true,y_pred))

              precision    recall  f1-score   support

           0       0.98      0.94      0.96      3746
           1       0.91      0.93      0.92      1161
           2       0.84      0.81      0.82       887
           3       0.97      0.99      0.98      5139

    accuracy                           0.95     10933
   macro avg       0.92      0.92      0.92     10933
weighted avg       0.95      0.95      0.95     10933



confusion metrics

In [57]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_true,y_pred)
cm

array([[3537,   70,  114,   25],
       [  10, 1083,    0,   68],
       [  74,   15,  715,   83],
       [   0,   19,   23, 5097]], dtype=int64)